[Service]
WorkingDirectory=/opt/ComfyUI-pixal-multiview
ExecStart=
ExecStart=/opt/ComfyUI/venv/bin/python /opt/ComfyUI-pixal-multiview/main.py --listen 0.0.0.0 --port 8188 --extra-model-paths-config /etc/comfyui/gpu3.yaml --input-directory /var/lib/comfyui/gpu3/input --output-directory /var/lib/comfyui/gpu3/output --temp-directory /var/lib/comfyui/gpu3/temp --user-directory /var/lib/comfyui/gpu3/user --disable-auto-launch
